config/routes.rb
Rails.application.routes.draw do

  get 'likes/index'

  resources :topics do
    resources :bookmarks, except: [ :index ]
  end

  resources :bookmarks do
    resources :likes, only: [:index, :create, :destroy]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'home/index'

  get 'home/about'

  root 'home#index'

  resources :users, only: [ :show ]

  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic

  has_many :likes, dependent: :destroy

  before_save :normalize_url
  after_create :set_image_url


  def set_image_url
    begin
      object = LinkThumbnailer.generate(url)
      Rails.logger.info "#{object.images.first.inspect}"
      update_attribute(:image_url, object.images.first.to_s)
    rescue
      Rails.logger.warn "Bad image url for bookmark #{self.id}"
    end
  end

  def normalize_url
    self.url = "http://#{self.url}" if URI.parse(self.url).scheme.nil?
    self.url = self.url
  end

  def pretty_url
    host = URI.parse(url).host.downcase
    host.start_with?('www.') ? host[4..-1] : host
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user

  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics

  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

    include Pundit
  
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_topic, except: [ :destroy ]

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @topic.bookmarks.new(bookmark_params)

    if @bookmark.save
      flash[:notice] = "Bookmark added to #{@bookmark.topic.title}!"
      redirect_to @bookmark.topic
    else
      flash[:alert] = "There was a problem adding this bookmark."
      redirect_to @bookmark.topic
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.destroy
      flash[:notice] = "Bookmark deleted!"
      redirect_to @bookmark.topic
    else
      flash[:alert] = "Unable to delete bookmark. Please try again."
      redirect_to @bookmark.topic
    end
  end

  def get_host_without_www(url)
    url = "http://#{url}" if URI.parse(url).scheme.nil?
    host = URI.parse(url).host.downcase
    host.start_with?('www.') ? host[4..-1] : host
  end

  private

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  layout "home"

  def index
  end

  def about
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create

    # You put the message-splitting and business
    # magic here.

     # Find the user by using params[:sender]
     # Check if user is nil, if so, create and save a new user
     @user = User.create_with(password: 'changeme').find_or_create_by(email: params[:sender])

     # Find the topic by using params[:subject]
     # Check if the topic is nil, if so, create and save a new topic
     @topic = Topic.create_with(user_id: @user).find_or_create_by(title: params[:subject])

     # Assign the url to a variable after retreiving it from params["body-plain"]
     @email_url = params["body-plain"]

     # Now that you're sure you have a valid user and topic, build and save a new bookmark
     @bookmark = @topic.bookmarks.create(url: @email_url)

    # Assuming all went well.
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      @bookmark = Bookmark.find(params[:bookmark_id])
      @topic = @bookmark.topic
      like = current_user.likes.build( bookmark_id: @bookmark.id )

      if like.save
        flash[:notice] = "Bookmark successfully liked!"
        redirect_to @bookmark.topic
      else
        flash[:alert] = "Something went wrong when liking. Please try again."
        redirect_to @bookmark.topic
      end
    end

    def destroy
      @bookmark = Bookmark.find(params[:bookmark_id])
      @topic = @bookmark.topic
      like = current_user.likes.find_by( bookmark_id: @bookmark.id )

      if like.destroy
        flash[:notice] = "Bookmark successfully unliked!"
        redirect_to @bookmark.topic
      else
        flash[:alert] = "Something went wrong when unliking. Please try again."
        redirect_to @bookmark.topic
      end
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

  # def after_sign_up_path_for(resource)
  #   @user = current_user
  #   @user
  # end
  #
  # def after_inactive_sign_up_path_for(resource)
  #   @user = current_user
  #   @user
  # end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  def index
    @topics = current_user.topics
  end

  # GET /topics/1
  def show
    @topic = Topic.find(params[:id])
    @bookmark = Bookmark.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to topics_url, notice: 'Topic was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def topic_params
      params.require(:topic).permit(:title, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper

  def get_host_without_www(url)
        url = "http://#{url}" if URI.parse(url).scheme.nil?
        host = URI.parse(url).host.downcase
        host.start_with?('www.') ? host[4..-1] : host
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="col-md-2 col-sm-2" style="text-align: center;">
  <div>
    <%= link_to image_tag(bookmark.image_url, class: "bookmark-image"), bookmark.url %>
  </div>
  <p><%= bookmark.pretty_url %></p>
  <div class="row" style="padding-bottom: 8px;">
    <small><%= render partial: 'likes/like', locals: { bookmark: bookmark } %> | <%= link_to 'Delete', bookmark, :method => :delete %></small>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<h5>Add a bookmark to this Placheolderr</h5>

<%= form_for [@topic, @bookmark] do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :url, placeholder: "Paste URL here" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/bookmarks/update.html.erb
<h1>Bookmarks#update</h1>
<p>Find me in app/views/bookmarks/update.html.erb</p>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div id="lpcolorhero">

  <div class="container-fluid" style="background-color: #D9230F; padding-top: 10%; min-height: 100%">

    <div class="col-md-5">
      <h1 id="lpheader1" style="padding-top: 5px; padding-left: 30px;">Meet Placeholderr.</h1>
      <h4 style="padding-left: 32px; color: white; font-family: 'Roboto', sans-serif; font-size: 20px; font-weight:400; margin-top: 30px;">Bookmarks just got social.</h4>

      <div class="row" style="width: 2000px; padding-left:30px; padding-top:20px;">
          <div class="col-md-1" ><%= button_to "Sign Up", new_user_registration_path, :method => :get, :class => 'ghost-button-transition'  %></div>
          <div class="col-md-1" ><%= button_to "Sign In", new_user_session_path, :class => 'ghost-button-transition'  %></div>
      </div>
    </div>

    <div class="col-md-7" style="margin-bottom:40px;">
      <img src="<%= asset_path( 'main_laptop.png' ) %>" />
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Placeholderr</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Placeholderr</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">About</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Contact</a></li>
            <li class="divider"></li>
            <li><%=link_to "My Placeholderrs", topics_path %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to "Logged in as #{current_user.first_name} #{current_user.last_name}", edit_user_registration_path, :class => 'navbar-link' %> </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
        <% else %>
          <li> <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %><span class="sr-only">(current)</span> </li>
          <li> <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

    <% if flash[:notice] %>
      <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>


</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Placeholderr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Placeholderr</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">About</a></li>
              <li><a href="#">FAQ</a></li>
              <li><a href="#">Contact</a></li>
              <li class="divider"></li>
              <li><%=link_to "My Placeholderrs", topics_path %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Logged in as #{current_user.first_name} #{current_user.last_name}", edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
        </ul>
      </div>
    </div>
    </nav>
  <% end %>

  <% if flash[:notice] %>
    <div class="alert alert-dismissible alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/likes/_like.html.erb
<div>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
  <% end %>
</div>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="margin-left: 5%;"><%= current_user.first_name %>'s Placeholderrs</h1>

        <% @topics.each do |topic| %>
            <div class = "row col-md-12 col-sm-12" style="margin-left: 5%;">
              <div class = "topic-head">
              <h3><%= link_to "#{topic.title}", topic %><h3>
                <small><p class="topic-head-small"><%= link_to 'Rename', edit_topic_path(topic) %> | <%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></p><small>
              </div>

              <div class="row col-md-10 col-sm-10" style="border: 0px; background-color: transparent;">
                <%= render topic.bookmarks %>
              </div>
            </div>

    <% end %>

<br>

<div style="margin-left: 6%;">
  <%= button_to 'New Topic', new_topic_path, :method => :get, :class => "btn btn-primary" %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class="container">

  <h3>
    <%= @topic.title %>
  </h3>
  <div class="row col-md-12 col-sm-12">
    <%= render @topic.bookmarks %>
  </div>

  <br />

<div class="row col-md-12 col-sm-12">
  <%= render partial: 'bookmarks/form', locals: { topic: @topic, bookmark: @bookmark } %>
</div>

</div>

app/views/users/show.html.erb
<h1>User Show View</h1>

<h2>My Bookmarks</h2>
<div class="row col-md-12 col-sm-12">
  <%= render current_user.bookmarks %>
</div>


<h2>My Likes</h2>
<%= render current_user.likes.collect(&:bookmark) %>